version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: echo "building app" 

  test:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: echo "testing app" 
  
  deploy:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: echo "deployed app" 

workflows:
  do-all-the-things:
    jobs:
      - test


